### ISSUE TITLE
All source references to HCA library_preparation_process.json are broken

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/synapseAnnotations#614] opened 2020-06-06 18:57 UTC
example here: 
https://github.com/Sage-Bionetworks/synapseAnnotations/blob/c4c0f4f25c48271877cd596b6356891edbacf1b8/synapseAnnotations/data/ngs.json#L173

**Comment by karawoo** [comment] 2020-06-07 00:45
This is a duplicate of #426 so I'm going to close this one

**Closed by karawoo** 2020-06-07 00:45 UTC

**Comment by allaway** [comment] 2020-06-07 00:48
Ah, sorry about that. I just came across it when trying to looking for more
information this morning and hastily filed the issue! 🙂
