### ISSUE TITLE
Resolve dataType for methylation and ChIPSeq

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/synapseAnnotations#252] opened 2017-10-18 23:43 UTC
For AMP-AD: currently we're calling the dataType of methylation and ChIPSeq data as "chromatinActivity" but this might not be the best way to go about it. 

Possible alternative: epigenomics for methylation, ChIPSeq, and ATACSeq.

**Comment by sgosline** [comment] 2017-10-24 19:08
I think we should keep data type as chromatinActivity, both because you are measuring the chromatin directly anyway, and epigenomics is too broad (can apply to post-transcriptional regulation)

**Comment by sgosline** [comment] 2017-10-24 20:22
Also how is this not a duplicate of #244 ?

**Comment by sgosline** [comment] 2017-12-05 21:32
Not in complete agreement but can re-open when we have more specific use case for transcription factor searches. Decision is to use `chromatinActivity`

**Closed by sgosline** 2017-12-05 21:32 UTC
Labels: naming convention
