### ISSUE TITLE
Using Synapse Table schemas for annotation info

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/synapseAnnotations#18] opened 2016-10-14 23:17 UTC
Upon discussing options for different types of columns (e.g. numeric) I had the thought that we might be trying to engineer something already solved - Synapse Table schemas could be used for annotation information. This is relevant because the new annotation related feature of `EntityView` HAS a Schema like all other Synapse Tables (which is the thing we're trying to enforce). It also has a 'scope' which is one of the features @sgosline was working towards (which annotations go with which files).

Though, it was rightly stated that if we wanted to address source info (Issue #13), this would not be sufficient.

Here's an example JSON representation of columns from a Synapse `EntityView`:

```
[
  {
    "columnType": "ENTITYID",
    "id": "2510",
    "name": "id"
  },
  {
    "columnType": "STRING",
    "id": "23543",
    "maximumSize": 256,
    "name": "name"
  },
  {
    "columnType": "DATE",
    "id": "4694",
    "name": "createdOn"
  },
  {
    "columnType": "INTEGER",
    "id": "4377",
    "name": "createdBy"
  },
  {
    "columnType": "ENTITYID",
    "id": "26640",
    "name": "parentId"
  },
  {
    "columnType": "ENTITYID",
    "id": "26641",
    "name": "projectId"
  },
  {
    "columnType": "DATE",
    "id": "23549",
    "name": "modifiedOn"
  },
  {
    "columnType": "INTEGER",
    "id": "4378",
    "name": "modifiedBy"
  },
  {
    "enumValues": [
      "csv",
      "txt"
    ],
    "columnType": "STRING",
    "id": "26991",
    "maximumSize": 50,
    "name": "fileType"
  }
]
```

Ideas:
1. We take part of this as a framework, and add other stuff.
1. We use the defined Synapse [ColumnModel](http://hud.rel.rest.doc.sagebase.org.s3-website-us-east-1.amazonaws.com/org/sagebionetworks/repo/model/table/ColumnModel.html) and [ColumnType](http://hud.rel.rest.doc.sagebase.org.s3-website-us-east-1.amazonaws.com/org/sagebionetworks/repo/model/table/ColumnType.html) to determine types.

Could be used as a testing step to assure that all columns are Synapse compatible.

**Comment by kdaily** [comment] 2016-10-14 23:31
Link to the relevant view: 

https://www.synapse.org/#!Synapse:syn7366616/tables/

**Comment by sgosline** [comment] 2016-10-20 18:22
I think we should take the minified yaml and create a sample table schema.

**Comment by kdaily** [comment] 2016-10-25 21:34
Wrote a script that takes the minified JSON to a `TableSchema`:

https://gist.github.com/kdaily/6e1cf231dcce466104b4e831f9bb77fc

**Comment by sgosline** [comment] 2016-10-26 15:27
Nice! Should we create a Synapse project that will house all annotation schemas?

**Comment by kdaily** [comment] 2016-10-27 00:08
@sgosline - Hmm, good question. I think so, but then the schemas that are actually used for a particular project (e.g. minimal + project specific) should be part of a `TableView` in the project they're being applied to. Or, for testing purposes, in a Synapse project for the annotations.

I grabbed https://www.synapse.org/annotation, but it seems someone has https://www.synapse.org/annotations already (and I don't have access maybe?) Is that someone here?

**Comment by sgosline** [comment] 2016-10-27 00:15
Yeah, the issue is that most annotations span single projects (hence the need for this group).

**Comment by kdaily** [comment] 2016-10-27 00:16
`TableView`s are not restricted to a project. You can add containers from different projects.

**Comment by kdaily** [comment] 2016-11-08 20:56
One thing to bring up is how to identify `TableView` `Schemas` that use a specific column definition that may be out of date. I filed a Jira to provide a service for this:

https://sagebionetworks.jira.com/browse/PLFM-4134

Anecdotally, John Hill notes that there are low-level methods existing to do this that could be exposed as a REST service.

**Comment by kdaily** [comment] 2017-01-25 00:22
#39 solves this. Should we move the rest of the files there, and update this repo to clarify no longer accepting JSON or YAML files here?

**Comment by sgosline** [comment] 2017-03-28 20:33
Yes! Let's close this issue.

**Closed** 2017-03-28 20:50 UTC
Labels: question
